package p3pserver

import (
	"crypto/subtle"
	"fmt"
	"strings"
	"time"
)

func (s *Server) VerifyCredential(header string) VerificationResult {
	payload, err := paymentHeaderPayload(header)
	if err != nil {
		return VerificationResult{Error: "Invalid P3P-Credential header format. Expected: Payment <base64url>"}
	}
	var credential Credential
	if err := DecodeJSON(payload, &credential); err != nil {
		return VerificationResult{Error: "Failed to decode credential from P3P-Credential header"}
	}
	invalid := func(message string) VerificationResult {
		return VerificationResult{Credential: &credential, Error: message}
	}
	challenge := credential.Challenge
	if challenge.ID == "" || challenge.Realm == "" || challenge.Request.Amount == "" {
		return invalid("Credential contains an incomplete challenge")
	}
	if challenge.Realm != s.config.Realm {
		return invalid(fmt.Sprintf("Challenge realm mismatch. Expected %q, got %q", s.config.Realm, challenge.Realm))
	}
	if len(challenge.Request.AvailablePaymentMethods) == 0 {
		return invalid("Challenge missing available payment methods")
	}
	expires, parseErr := time.Parse(time.RFC3339Nano, challenge.Expires)
	if parseErr != nil || !expires.After(time.Now()) {
		return invalid("Challenge has expired")
	}
	requestEncoded, encodeErr := EncodeJSON(challenge.Request)
	if encodeErr != nil {
		return invalid("Credential contains an incomplete challenge")
	}
	expected := computeChallengeID(deriveChallengeHMACKey(s.config.ClientSecret), challenge.Realm, challenge.Intent, requestEncoded, challenge.Expires)
	if len(expected) != len(challenge.ID) || subtle.ConstantTimeCompare([]byte(expected), []byte(challenge.ID)) != 1 {
		return invalid("Challenge HMAC verification failed. The challenge was not generated by this server.")
	}
	if strings.TrimSpace(credential.Payload.Token) == "" {
		return invalid("Credential missing payment token")
	}
	if credential.Payload.PaymentMethod == "" {
		return invalid("Credential missing selected payment method")
	}
	accepted := false
	for _, method := range challenge.Request.AvailablePaymentMethods {
		if method == credential.Payload.PaymentMethod {
			accepted = true
		}
	}
	if !accepted {
		return invalid(fmt.Sprintf("Selected payment method %s is not accepted by this challenge", credential.Payload.PaymentMethod))
	}
	configured := false
	for _, method := range s.config.AvailablePaymentMethods {
		if method == credential.Payload.PaymentMethod {
			configured = true
		}
	}
	if !configured {
		return invalid(fmt.Sprintf("Selected payment method %s is not enabled on this server", credential.Payload.PaymentMethod))
	}
	return VerificationResult{Valid: true, Credential: &credential}
}

func paymentHeaderPayload(header string) (string, error) {
	value := strings.TrimSpace(header)
	if !strings.HasPrefix(value, "Payment ") {
		return "", fmt.Errorf("invalid header")
	}
	value = strings.TrimSpace(strings.TrimPrefix(value, "Payment "))
	if value == "" {
		return "", fmt.Errorf("empty payload")
	}
	if _, err := DecodeBase64URL(value); err != nil {
		return "", err
	}
	return value, nil
}
